# Generated by Django 4.2.1 on 2023-05-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0002_cardquestion_subtopic_choice_cardquestion_subtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cardquestion',
            name='resources',
            field=models.ManyToManyField(related_name='questions', to='flash_cards.resource'),
        ),
    ]
