# Generated by Django 4.2.1 on 2023-05-24 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0004_remove_cardquestion_resources_cardquestion_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='subtopic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='flash_cards.subtopic'),
            preserve_default=False,
        ),
    ]
